### ISSUE TITLE
image1

### ISSUE THREAD

**Issue by KimGona** [coolho1129/Metaverse-Background-Research#2]
![image1](https://github.com/coolho1129/Metaverse-Background-Research/assets/75716291/fda1fdc7-d1db-4c61-aaf1-2c0013bbb344)
![image7](https://github.com/coolho1129/Metaverse-Background-Research/assets/75716291/6f286494-8923-41da-8283-61e99156ff11)
![image6](https://github.com/coolho1129/Metaverse-Background-Research/assets/75716291/5fdc0c24-b4dd-42b7-a39d-ee6b2454aa34)
![image5](https://github.com/coolho1129/Metaverse-Background-Research/assets/75716291/8297aa8e-22c2-486e-8d66-57e799c28376)
![image4](https://github.com/coolho1129/Metaverse-Background-Research/assets/75716291/3e58b108-a66b-4b88-a192-1d5348d44206)
![image3](https://github.com/coolho1129/Metaverse-Background-Research/assets/75716291/f62a5d3c-320c-4c75-84c8-188effab307b)
![image2](https://github.com/coolho1129/Metaverse-Background-Research/assets/75716291/7a1baa5d-517f-42fb-b217-b0ed41b6377c)

**Comment by coolho1129** [comment]
확인완료
